// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Generates a unique and visually appealing image for each Loot Box.
 *
 * - generateLootBoxImage - A function that handles the loot box image generation process.
 * - GenerateLootBoxImageInput - The input type for the generateLootBoxImage function.
 * - GenerateLootBoxImageOutput - The return type for the generateLootBoxImage function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateLootBoxImageInputSchema = z.object({
  theme: z.string().describe('The theme of the loot box image. Examples: futuristic, medieval, cyberpunk.'),
  contentDescription: z.string().describe('A description of the contents inside the loot box.'),
});
export type GenerateLootBoxImageInput = z.infer<typeof GenerateLootBoxImageInputSchema>;

const GenerateLootBoxImageOutputSchema = z.object({
  imageUrl: z.string().describe('The generated image URL for the loot box.'),
});
export type GenerateLootBoxImageOutput = z.infer<typeof GenerateLootBoxImageOutputSchema>;

export async function generateLootBoxImage(input: GenerateLootBoxImageInput): Promise<GenerateLootBoxImageOutput> {
  return generateLootBoxImageFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateLootBoxImagePrompt',
  input: {schema: GenerateLootBoxImageInputSchema},
  output: {schema: GenerateLootBoxImageOutputSchema},
  prompt: `Generate a unique and visually appealing image for a loot box with the following characteristics:

Theme: {{{theme}}}
Content Description: {{{contentDescription}}}

The image should be high-quality and engaging, reflecting the potential rewards inside the box.

Respond with the generated image URL.
`,
});

const generateLootBoxImageFlow = ai.defineFlow(
  {
    name: 'generateLootBoxImageFlow',
    inputSchema: GenerateLootBoxImageInputSchema,
    outputSchema: GenerateLootBoxImageOutputSchema,
  },
  async input => {
    const {media} = await ai.generate({
      model: 'googleai/gemini-2.0-flash-exp',
      prompt: `Generate an image of a loot box with the following characteristics:

Theme: ${input.theme}
Content Description: ${input.contentDescription}`,
      config: {
        responseModalities: ['TEXT', 'IMAGE'],
      },
    });

    return {imageUrl: media.url!};
  }
);
